from pathlib import Path
import importlib.util,json

ROOT=Path(__file__).resolve().parents[1]
spec=importlib.util.spec_from_file_location("pm",ROOT/"scripts/profile_manager.py")
pm=importlib.util.module_from_spec(spec);spec.loader.exec_module(pm)
manifest=json.loads((ROOT/"manifest.json").read_text())
lines=[
"# Profile Catalog","",
"> Generated by `python scripts/generate-docs.py`. Do not edit manually.","",
f"Pack version: `{manifest['version']}`","",
]
for p in sorted((ROOT/"profiles").glob("*.json")):
    if p.stem=="catalog":continue
    data=json.loads(p.read_text())
    eff=pm.resolve_profile(p.stem)
    core=set(pm.resolve_profile("core"))
    delta=eff if p.stem=="core" else [s for s in eff if s not in core]
    lines += [
        f"## `{p.stem}`","",
        data.get("description",""),"",
        f"- Effective skills: **{len(eff)}**",
        f"- Project delta: **{len(delta)}**","",
        "### Project-delta skills","",
    ]
    lines += [f"- `{s}`" for s in delta] or ["- None"]
    lines += [""]
out=ROOT/"docs/PROFILE-CATALOG.md"
out.parent.mkdir(exist_ok=True)
out.write_text("\n".join(lines).rstrip()+"\n",encoding="utf-8")
print("Generated:",out)
